### ISSUE TITLE
🐛 Weird interaction with pytest and vscode

### ISSUE THREAD

**Issue by Gistbatch** [cda-tum/mqt-qmap#375]
### Environment information

- OS: Ubuntu 22.04
- mqt.qmap version: 2.4.0
- python version: 3.10.12
- pytest version: 7.4.2
- pdm version: 2.9.1
- vscode version: 1.82 with python extension v2023.16.0

### Description

Using `qmap` leads to a parsing error during test discovery with `pytest`:

```
2023-09-12 15:17:52.978 [error] Error discovering pytest tests:
 [SyntaxError: 
	at JSON.parse (<anonymous>)
	at a.runTestDiscovery (~/.vscode/extensions/ms-python.python-2023.16.0/out/client/extension.js:2:825931)
	at async Promise.all (index 0)
	at async _.refreshTestData (~/.vscode/extensions/ms-python.python-2023.16.0/out/client/extension.js:2:867010)
	at async A.refreshTestDataInternal (~/.vscode/extensions/ms-python.python-2023.16.0/out/client/extension.js:2:853424)]
```

Running `pytest` manually results in a core dump:
```
╰─ ./.venv/bin/python -m pytest --collect-only 
[1]    1282921 illegal hardware instruction (core dumped)  ./.venv/bin/python -m pytest --collect-only
```

### Expected behavior

`pytest` should not be influenced by the `qmap` package.

### How to Reproduce

In an empty directory, run the following (also works with `pip`, but needs some boilerplate):
1. `pdm venv create`
2. `pdm init` (and select the freshly created environment)
3. `pdm add pytest mqt-qmap`
4. `echo 'from mqt import qmap' >> src/example_package/__init__.py`
5. `echo 'from src import example_package' >> tests/test_qmap.py`
6. `./.venv/bin/python -m pytest --collect-only`

**Comment by burgholzer** [comment]
For what it's worth, this is unrelated to `pytest`, as a simple
```bash
python -c 'from mqt import qmap'
```
also results in 
```console
Illegal instruction (core dumped)
```
under the above circumstances.

I also tested on macOS, where this does not seem to be a problem.
